# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # pod 'FLKAutoLayout'
  # Pods for DemoLogin
  
  pod 'ReactiveObjC'
  pod 'OCMock'
  pod 'AFNetworking'
  pod 'JSONModel'
  pod 'OHHTTPStubs'

  target 'DemoLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
